#!/bin/bash

##############################################################################
# gc-agent.sh — 기술 부채 관리 및 관측성 수집
#
# 모드:
#   --scan: debt-report.md 스캔 및 업데이트
#   --collect: logs/ 디렉토리에 메트릭 및 이벤트 수집
#   --scan --collect: 스캔 후 자동으로 logs 수집
#
##############################################################################

set -euo pipefail

HARNESS_ROOT="${HARNESS_ROOT:-.}"
HARNESS_PHASE="${HARNESS_PHASE:-development}"
MODE="scan"  # 기본값

# 옵션 파싱
SCAN=false
COLLECT=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --scan)
      SCAN=true
      shift
      ;;
    --collect)
      COLLECT=true
      shift
      ;;
    *)
      shift
      ;;
  esac
done

# 기본값: --scan이 지정되지 않으면 --scan 실행
if [[ "$SCAN" == false && "$COLLECT" == false ]]; then
  SCAN=true
fi

DEBT_REPORT="${HARNESS_ROOT}/.harness/reports/debt-report.md"
LAST_CHECK="${HARNESS_ROOT}/.harness/reports/last-check.json"
CONTEXT_FILE="${HARNESS_ROOT}/.harness/context/current.md"
LOGS_DIR="${HARNESS_ROOT}/logs"

TODAY=$(date +%Y-%m-%d)
METRICS_FILE="${LOGS_DIR}/metrics/${TODAY}.jsonl"
TRACES_FILE="${LOGS_DIR}/traces/${TODAY}.jsonl"
EVENTS_FILE="${LOGS_DIR}/events/${TODAY}.jsonl"

# ============================================================================
# SCAN 모드: debt-report.md 생성
# ============================================================================
scan_debt() {
  echo ">>> [gc-agent] Scanning for technical debt..."

  # debt-report.md 초기화
  mkdir -p "$(dirname "$DEBT_REPORT")"
  cat > "$DEBT_REPORT" << 'EOF'
---
title: Technical Debt Report
watches:
  - scripts/
  - linters/
last_scanned: $(date -u +%Y-%m-%dT%H:%M:%SZ)
---

# Technical Debt Report

## CRITICAL Issues

(None detected yet)

## WARNING Issues

(None detected yet)

## INFO Issues

(None detected yet)

---
Generated by gc-agent.sh
EOF

  # 실제 스캔 로직은 여기에 추가
  # 지금은 템플릿만 생성
}

# ============================================================================
# COLLECT 모드: logs/ 디렉토리에 수집
# ============================================================================
collect_logs() {
  echo ">>> [gc-agent] Collecting metrics and events..."

  mkdir -p "${LOGS_DIR}/"{metrics,traces,events}

  # 1. last-check.json에서 constraint 결과 → logs/events
  if [[ -f "$LAST_CHECK" ]]; then
    local timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ)
    local pass_rate=0

    # JSON에서 pass_rate 추출
    if grep -q '"pass_rate"' "$LAST_CHECK"; then
      pass_rate=$(grep -o '"pass_rate":[0-9.]*' "$LAST_CHECK" | grep -o '[0-9.]*' || echo "0")
    fi

    # 메트릭 기록
    echo "{\"timestamp\":\"${timestamp}\",\"metric_name\":\"constraint_pass_rate\",\"value\":${pass_rate},\"unit\":\"%\",\"source\":\"constraint-check\"}" >> "$METRICS_FILE"

    # FAIL 이벤트가 있으면 기록
    if grep -q '"status":"FAIL"' "$LAST_CHECK"; then
      while IFS= read -r line; do
        if echo "$line" | grep -q '"constraint_id"'; then
          local constraint_id=$(echo "$line" | grep -o '"constraint_id":"[^"]*"' | grep -o '[^"]*"$' | tr -d '"')
          echo "{\"timestamp\":\"${timestamp}\",\"event_type\":\"constraint_fail\",\"constraint_id\":\"${constraint_id}\",\"severity\":\"WARN\",\"detail\":\"constraint failed\"}" >> "$EVENTS_FILE"
        fi
      done < "$LAST_CHECK"
    fi
  fi

  # 2. debt-report.md에서 CRITICAL/WARN → logs/events
  if [[ -f "$DEBT_REPORT" ]]; then
    local timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ)

    if grep -q "^## CRITICAL" "$DEBT_REPORT"; then
      local critical_count=$(grep -A 100 "^## CRITICAL" "$DEBT_REPORT" | grep -c "^- " || echo "0")
      if [[ $critical_count -gt 0 ]]; then
        echo "{\"timestamp\":\"${timestamp}\",\"event_type\":\"debt_detected\",\"constraint_id\":null,\"severity\":\"CRITICAL\",\"detail\":\"${critical_count} critical debt items\"}" >> "$EVENTS_FILE"
      fi
    fi
  fi

  # 3. context/current.md 줄 수 → logs/metrics (budget 계산)
  if [[ -f "$CONTEXT_FILE" ]]; then
    local timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ)
    local line_count=$(wc -l < "$CONTEXT_FILE" || echo "0")
    local max_budget=2000
    local budget_pct=$(echo "scale=1; ($line_count * 100) / $max_budget" | bc -l)

    echo "{\"timestamp\":\"${timestamp}\",\"metric_name\":\"context_budget_pct\",\"value\":${budget_pct},\"unit\":\"%\",\"source\":\"context-loader\"}" >> "$METRICS_FILE"

    # budget_warn_streak 업데이트
    update_budget_warn_streak "$budget_pct"
  fi

  # 4. 실행 트레이스 기록
  local timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ)
  echo "{\"timestamp\":\"${timestamp}\",\"script\":\"scripts/gc-agent.sh\",\"mode\":\"collect\",\"duration_ms\":0,\"exit_code\":0}" >> "$TRACES_FILE"

  echo ">>> [gc-agent] Logs collected to: ${LOGS_DIR}/"
}

# ============================================================================
# budget_warn_streak 업데이트
# ============================================================================
update_budget_warn_streak() {
  local current_pct="$1"
  local threshold=80

  # last-check.json 초기화
  mkdir -p "$(dirname "$LAST_CHECK")"

  if [[ ! -f "$LAST_CHECK" ]]; then
    echo '{"status":"PASS","budget_warn_streak":0,"constraints":{}}' > "$LAST_CHECK"
  fi

  # streak 계산: 최근 logs/metrics에서 80% 초과 연속 확인
  local streak=0
  if [[ -f "$METRICS_FILE" ]]; then
    while IFS= read -r line; do
      if echo "$line" | grep -q '"metric_name":"context_budget_pct"'; then
        local value=$(echo "$line" | grep -o '"value":[0-9.]*' | grep -o '[0-9.]*')
        if (( $(echo "$value > $threshold" | bc -l) )); then
          streak=$((streak + 1))
        else
          streak=0
        fi
      fi
    done < "$METRICS_FILE"
  fi

  # last-check.json 업데이트
  if command -v jq &> /dev/null; then
    jq ".budget_warn_streak=$streak" "$LAST_CHECK" > "${LAST_CHECK}.tmp" && mv "${LAST_CHECK}.tmp" "$LAST_CHECK"
  fi
}

# ============================================================================
# 메인 실행
# ============================================================================

if [[ "$SCAN" == true ]]; then
  scan_debt
fi

if [[ "$COLLECT" == true ]]; then
  collect_logs
fi

echo ">>> [gc-agent] Done"
exit 0
